# Generated by Django 3.1.5 on 2021-01-12 03:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idConta', models.IntegerField()),
                ('idPessoa', models.IntegerField()),
                ('saldo', models.FloatField()),
                ('limiteSaqueDiario', models.IntegerField()),
                ('flagAtivo', models.BooleanField()),
                ('tipoConta', models.IntegerField()),
                ('dataCriacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
