# Generated by Django 3.1.5 on 2021-01-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('idPessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('dataNascimento', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
